### PR TITLE
Add Python Cheque Generator

### PR DESCRIPTION
**Pull request by DonGuillotine**
This commit adds a simple Python program for a cheque generator. The program takes the name, date, and amount as input and outputs the name, date, and amount in words. 

The conversion of numbers to words is handled by a simple function. I created a basic GUI using Tkinter for user input.

### CODE REVIEW

**Comment by gmmkmtgk** [comment]
Hi @DonGuillotine 
Please add sample input and output photos

**Comment by DonGuillotine** [comment]
You mean screenshots of the Cheque UI? @gmmkmtgk

**Comment by gmmkmtgk** [comment]
@DonGuillotine yeah given input and corresponding output

Give for numbers like

1034689
23879
233333

**Comment by DonGuillotine** [comment]
> @DonGuillotine yeah given input and corresponding output
> 
> Give for numbers like
> 
> 1034689 23879 233333

@gmmkmtgk Would I add the screenshots to to a `Readme.md` file?

**Comment by gmmkmtgk** [comment]
no here only in pr

**Comment by DonGuillotine** [comment]
Hello @gmmkmtgk I have given input and corresponding output for numbers like 1034689, 23879 and 233333

Here is the screenshot: 
Screenshot (323)

**Comment by gmmkmtgk** [comment]
@DonGuillotine in india on cheques writting million is not allowed please use lakhs 

So add a variable select country use two country as of now only India and US

Later we can add more countries and languages

**Comment by DonGuillotine** [comment]
@gmmkmtgk I have:
- Introduced support for converting numbers to words based on US and Indian numbering systems.
- Implemented 'lakhs' and 'crores' for the Indian numbering format.
- Refined the user interface with a dropdown to choose between US and India systems.
- Improved overall code structure for better readability and maintainability.

Here is a Screenshot: 
Screenshot (324)

**Comment by gmmkmtgk** [comment]
@DonGuillotine great job 
consider solving other issues also

**Pull request merged**
