### PR TITLE
Implementing facebook prophet

### PR DESCRIPTION
**Pull request by carlosfrodrigues**
Closes Issue #27

### CODE REVIEW

**Comment by gmmkmtgk** [comment]
@carlosfrodrigues 
Could you show results that came after running this file

And please also add comments in code to show what is going on

**Comment by carlosfrodrigues** [comment]
I added the comments. About the results, I'm getting a csv with new lines with the predictions. 
In this example I was predicting 30 days for the BASML stock:
image

**Comment by gmmkmtgk** [comment]
What are these columns representing?

And will merge the pr LGTM but it would be really great if you could backtest it by using old data basically leave current month and use 13 months to 12 months and match the prediction by the month you left

**Comment by carlosfrodrigues** [comment]
So the columns are: trend, yhat_lower, yhat_upper, trend_lower, trend_upper, additive_terms, additive_terms_lower, additive_terms_upper, weekly, weekly_lower, weekly_upper, multiplicative_terms, multiplicative_terms_lower, multiplicative_terms_upper and yhat.

Being `yhalt` the predicted value for the time series at a specific point in the future. It's the main output of the Prophet model and represents the model's best estimate of the future values of the time series.
I created on the script a option for making a backtest! It will compare with the yhalt column.

**Pull request merged**
